version: '3'
services:
  # broker-rabbitmq:
  #   image: "rabbitmq:3.7.14-management"
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=rabbit_user
  #     - RABBITMQ_DEFAULT_PASS=rabbit_password
  # db-postgres:
  #   image: "postgres:11.2"
  #   environment:
  #     - POSTGRES_USER=db_user 
  #     - POSTGRES_PASSWORD=db_password
  # migration:
  #   build: .
  #   environment:
  #     - APP_ENV=${APP_ENV}
  #   command: flask db init && flask db migrate -m "Initial migration." && flask db upgrade
  #   depends_on:
  #     - db-postgres
  api:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:5001"
    environment:
      - APP_ENV=${APP_ENV}
      - EMAIL_USER='dixon1e@gmail.com'
      - EMAIL_PASS='YOURPASS'
      - SQLALCHEMY_DATABASE_URI=postgres://USER:PASS@lallah.db.elephantsql.com:5432/qfdbtxlm # sqlite:///site.db
      - STATIC_URL=/static
      - STATIC_PATH=/flaskblog/static
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    # depends_on:
    #   - broker-rabbitmq
    #   - db-postgres
    #   - migration
  # api-worker:
  #     build: .
  #     command: celery worker --workdir=. -A  tasks.celery --loglevel=info
  #     environment:
  #       - APP_ENV=${APP_ENV}
  #     depends_on:
  #       - broker-rabbitmq
  #       - db-postgres
  #       - migration
  # api-beat:
  #     build: .
  #     command: celery beat -A tasks.celery --loglevel=info
  #     environment:
  #       - APP_ENV=${APP_ENV}
  #     depends_on:
  #       - broker-rabbitmq
  #       - db-postgres
  #       - migration
